# Generated by Django 6.1.1 on 2026-09-29 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('kind', models.CharField(default='behavioural', max_length=20)),
                ('job_id', models.CharField(blank=True, default='', max_length=255)),
                ('job_title', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='mock', max_length=20)),
                ('interval_days', models.FloatField(default=1)),
                ('next_due', models.DateField()),
                ('reps', models.IntegerField(default=0)),
                ('last_score', models.IntegerField(blank=True, null=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('mastered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InboxSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, default='', max_length=500)),
                ('subject', models.TextField(blank=True, default='')),
                ('sender', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(max_length=20)),
                ('suggested_status', models.CharField(blank=True, default='', max_length=40)),
                ('job_id', models.CharField(blank=True, default='', max_length=255)),
                ('job_title', models.TextField(blank=True, default='')),
                ('company', models.TextField(blank=True, default='')),
                ('snippet', models.TextField(blank=True, default='')),
                ('mentions_date', models.CharField(blank=True, default='', max_length=80)),
                ('state', models.CharField(default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=255)),
                ('job_title', models.TextField(blank=True, default='')),
                ('company', models.TextField(blank=True, default='')),
                ('scheduled_on', models.DateField()),
                ('stage', models.CharField(choices=[('screen', 'Recruiter screen'), ('technical', 'Technical'), ('onsite', 'Panel / on-site'), ('final', 'Final')], default='screen', max_length=20)),
                ('done_tasks', models.JSONField(blank=True, default=list)),
                ('logged', models.BooleanField(default=False)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('felt', models.IntegerField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question', models.TextField(blank=True, default='')),
                ('text', models.TextField()),
                ('skills', models.JSONField(blank=True, default=list)),
                ('star', models.JSONField(blank=True, default=dict)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('job_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_baselines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
