# Generated by Django 6.1.1 on 2026-09-30 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('role', models.CharField(blank=True, default='', max_length=200)),
                ('kind', models.CharField(default='other', max_length=20)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('link', models.CharField(blank=True, default='', max_length=400)),
                ('job_id', models.CharField(blank=True, default='', max_length=255)),
                ('how_met', models.CharField(blank=True, default='', max_length=300)),
                ('notes', models.TextField(blank=True, default='')),
                ('next_step', models.CharField(blank=True, default='', max_length=300)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('last_contacted', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('job_id', models.CharField(blank=True, default='', max_length=255)),
                ('base_monthly', models.FloatField(default=0)),
                ('currency', models.CharField(default='TT$', max_length=4)),
                ('bonus_pct', models.FloatField(default=0)),
                ('signing', models.FloatField(default=0)),
                ('leave_days', models.IntegerField(default=0)),
                ('remote_days', models.IntegerField(default=0)),
                ('commute_minutes', models.IntegerField(default=0)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='considering', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
