# Generated by Django 6.1.1 on 2026-09-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.TextField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('from_status', models.CharField(blank=True, max_length=40)),
                ('to_status', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
